import type { Ability, Character, Weapon } from "./types";

// Abilities: include the specified examples and cover all types
export const MOCK_ABILITIES: Ability[] = [
  {
    id: "rail-shot",
    name: "Rail Shot",
    abilityType: "detonator",
    damageType: "kinetic",
    damage: 25,
    detonates: true,
    splashPct: 30,
    synergyHint: "Pairs well with: Suppressive Burst",
    allowedClasses: ["vanguard"],
  },
  {
    id: "suppressive-burst",
    name: "Suppressive Burst",
    abilityType: "prime",
    damageType: "arc",
    damage: 12,
    primes: 1,
    splashPct: 40,
    synergyHint: "Best used against primed targets",
    allowedClasses: ["vanguard"],
  },
  {
    id: "overwatch",
    name: "Overwatch",
    abilityType: "prime",
    damageType: "thermal",
    damage: 10,
    primes: 1,
    splashPct: 10,
    synergyHint: "Maintain pressure from range",
    allowedClasses: ["vanguard"],
  },
  {
    id: "void-lance",
    name: "Void Lance",
    abilityType: "detonator",
    damageType: "void",
    damage: 22,
    detonates: true,
    splashPct: 20,
    synergyHint: "Executes staggered foes",
    allowedClasses: ["infiltrator"],
  },
  // Hybrid removed; converted to detonator example
  {
    id: "arc-net",
    name: "Arc Net",
    abilityType: "detonator",
    damageType: "arc",
    damage: 16,
    detonates: true,
    splashPct: 15,
    synergyHint: "Detonates arc primes in a small area",
    allowedClasses: ["technician"],
  },
  {
    id: "thermal-grenade",
    name: "Thermal Grenade",
    abilityType: "prime",
    damageType: "thermal",
    damage: 14,
    primes: 1,
    splashPct: 35,
    synergyHint: "Area denial against clustered enemies",
    allowedClasses: ["technician", "mage"],
  },
  {
    id: "kinetic-barrage",
    name: "Kinetic Barrage",
    abilityType: "detonator",
    damageType: "kinetic",
    damage: 20,
    detonates: true,
    splashPct: 25,
    allowedClasses: ["vanguard"],
  },
  {
    id: "void-siphon",
    name: "Void Siphon",
    abilityType: "prime",
    damageType: "void",
    damage: 11,
    primes: 1,
    splashPct: 10,
    allowedClasses: ["infiltrator"],
  },
  {
    id: "shockwave",
    name: "Shockwave",
    abilityType: "detonator",
    damageType: "arc",
    damage: 18,
    detonates: true,
    splashPct: 30,
    allowedClasses: ["technician"],
  },
  {
    id: "ember-strike",
    name: "Ember Strike",
    abilityType: "detonator",
    damageType: "thermal",
    damage: 17,
    detonates: true,
    splashPct: 20,
    allowedClasses: ["mage"],
  },
  {
    id: "phase-bolt",
    name: "Phase Bolt",
    abilityType: "detonator",
    damageType: "void",
    damage: 19,
    detonates: true,
    splashPct: 15,
    allowedClasses: ["infiltrator"],
  },
];

export const MOCK_WEAPONS: Weapon[] = [
  {
    id: "none",
    name: "None",
    basicMult: 0.85,
    basicType: "kinetic",
  },
  {
    id: "sidearm",
    name: "Sidearm",
    basicMult: 1.30,
    basicType: "kinetic",
  },
  {
    id: "shock-baton",
    name: "Shock Baton",
    basicMult: 1.25,
    basicType: "arc",
  },
  {
    id: "flame-pistol",
    name: "Flame Pistol",
    basicMult: 1.25,
    basicType: "thermal",
  },
  {
    id: "void-blade",
    name: "Void Blade",
    basicMult: 1.25,
    basicType: "void",
  },
  {
    id: "kinetic-rifle",
    name: "Kinetic Rifle",
    basicMult: 1.25,
    basicType: "kinetic",
  },
  {
    id: "heavy-blade",
    name: "Heavy Blade",
    totalDamageMult: 1.20,
    basicType: "kinetic",
  },
  {
    id: "det-gauntlet",
    name: "Detonator Gauntlet",
    detonationDirectMult: 1.25,
    detonationSplashMult: 1.50,
    basicType: "void",
  },
  {
    id: "shield-emitter",
    name: "Shield Emitter",
    maxShBonus: 40,
    basicType: "arc",
  },
  {
    id: "medgel-frame",
    name: "Medgel Frame",
    maxHpBonus: 40,
    basicType: "thermal",
  },
  {
    id: "overcharger",
    name: "Overcharger",
    superGainMult: 1.25,
    basicType: "arc",
  },
];

export const MOCK_CHARACTERS: Character[] = [
  {
    id: "nova",
    name: "Nova",
    className: "vanguard",
    maxSlots: 5,
    selectedAbilityIds: [],
  },
  {
    id: "halley",
    name: "Halley",
    className: "mage",
    maxSlots: 5,
    selectedAbilityIds: [],
  },
  {
    id: "tess",
    name: "Tess",
    className: "technician",
    maxSlots: 5,
    selectedAbilityIds: [],
  },
];


